.ifdef DEBUG
CFLAGS=			-std=gnu99 -Wall -g3 -O0 -DDEBUG
.else
CFLAGS=			-std=gnu99 -Wall
.endif
KMOD=			clearram
SRCS=			subr_amd64.c subr_clear.c subr_host.c subr_map.c subr_FreeBSD.c clearram.c

.include <bsd.kmod.mk>
# vim:filetype=make
